/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DataSets } from "./DataSets";
export * as factories from "./factories";
export { DataSets__factory } from "./factories/DataSets__factory";
